export const events = [
  {
    slug: "react-india-2024",
    image: "/images/event1.png",
    title: "React India 2024",
    location: "Goa, India",
    date: "October 17-19, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "aws-community-day-bengaluru",
    image: "/images/event2.png",
    title: "AWS Community Day",
    location: "Bengaluru, Karnataka",
    date: "March 23, 2024",
    time: "8:00 AM - 5:00 PM",
  },
  {
    slug: "jsfoo-2024",
    image: "/images/event3.png",
    title: "JSFoo 2024",
    location: "Pune, Maharashtra",
    date: "August 24, 2024",
    time: "9:30 AM - 6:00 PM",
  },
  {
    slug: "devfest-delhi",
    image: "/images/event4.png",
    title: "Google DevFest",
    location: "New Delhi, Delhi",
    date: "December 1, 2024",
    time: "10:00 AM - 5:00 PM",
  },
  {
    slug: "ethindia-2024",
    image: "/images/event5.png",
    title: "ETHIndia Hackathon",
    location: "Bengaluru, Karnataka",
    date: "December 6-8, 2024",
    time: "48 Hours",
  },
  {
    slug: "pycon-india-2024",
    image: "/images/event6.png",
    title: "PyCon India",
    location: "Hyderabad, Telangana",
    date: "September 20-23, 2024",
    time: "9:00 AM - 5:30 PM",
  },
  {
    slug: "agile-india-2024",
    image: "/images/event1.png",
    title: "Agile India",
    location: "Bengaluru, Karnataka",
    date: "July 24-26, 2024",
    time: "8:30 AM - 6:00 PM",
  },
  {
    slug: "smart-india-hackathon",
    image: "/images/event2.png",
    title: "Smart India Hackathon",
    location: "Multiple Cities",
    date: "November 14-16, 2024",
    time: "72 Hours",
  },
  {
    slug: "open-source-summit-india",
    image: "/images/event3.png",
    title: "Open Source Summit",
    location: "Mumbai, Maharashtra",
    date: "May 10-11, 2024",
    time: "9:00 AM - 5:00 PM",
  },
  {
    slug: "react-native-meetup-chennai",
    image: "/images/event4.png",
    title: "React Native Meetup",
    location: "Chennai, Tamil Nadu",
    date: "June 15, 2024",
    time: "10:30 AM - 4:00 PM",
  },
  {
    slug: "gophercon-india",
    image: "/images/event5.png",
    title: "GopherCon India",
    location: "Pune, Maharashtra",
    date: "November 8-9, 2024",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "nullcon-goa",
    image: "/images/event6.png",
    title: "Nullcon Security Conf",
    location: "Goa, India",
    date: "February 28 - Mar 2, 2025",
    time: "8:00 AM - 7:00 PM",
  }
];